apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-probe-app
  namespace: probes-lab-$STUDENT_NAME
spec:
  replicas: 1
  selector:
    matchLabels: { app: tcp-probe-app }
  template:
    metadata:
      labels: { app: tcp-probe-app }
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports: [{containerPort: 6379}]
        livenessProbe:
          tcpSocket: { port: 6379 }
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          tcpSocket: { port: 6379 }
          initialDelaySeconds: 3
