apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lab04-$STUDENT_NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      tier: api
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
        - name: httpbin
          image: kong/httpbin
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /get
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
