apiVersion: apps/v1
kind: Deployment
metadata: { name: webapp-green, namespace: deploy-lab-$STUDENT_NAME }
spec:
  replicas: 2
  selector:
    matchLabels: { app: webapp-bg, version: green }
  template:
    metadata: { labels: { app: webapp-bg, version: green } }
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports: [{containerPort: 80}]
        command: ["/bin/sh", "-c"]
        args: ["echo '<h1 style=\"color:green\">GREEN</h1>' \
          > /usr/share/nginx/html/index.html; nginx -g 'daemon off;'"]
