apiVersion: v1
kind: Pod
metadata: { name: multi-container-app, namespace: obs-lab-$STUDENT_NAME }
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c',
      'while true; do echo "APP: req"; sleep 3; done']
  - name: sidecar
    image: busybox
    command: ['sh', '-c',
      'while true; do echo "SIDECAR: metrics"; sleep 5; done']
